config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'

  resources :users, only: [:index, :show, :new, :edit, :create, :destroy]
  resources :books, only: [:index, :show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    resources :holidays, only: [:create, :destroy]
    resource :weeks, only: [:create, :destroy]
    resource :fris, only: [:create, :destroy]
    resource :mons, only: [:create, :destroy]
    resource :sats, only: [:create, :destroy]
    resource :thus, only: [:create, :destroy]
    resource :tues, only: [:create, :destroy]
    resource :weds, only: [:create, :destroy]
  end
  get "past" => 'books#index2'
  resources :momments, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :holidays, dependent: :destroy
  has_many :weeks, dependent: :destroy
  has_many :mons, dependent: :destroy
  has_many :thus, dependent: :destroy
  has_many :tues, dependent: :destroy
  has_many :sats, dependent: :destroy
  has_many :weds, dependent: :destroy
  has_many :fris, dependent: :destroy

  validates :start_i, uniqueness: true
  validates :finish_i, uniqueness: true

  def week_by?(n)
    weeks.exists?(book_id: n)
  end

  def mon_by?(n)
    mons.exists?(book_id: n)
  end
  def tue_by?(n)
    tues.exists?(book_id: n)
  end
  def wed_by?(n)
    weds.exists?(book_id: n)
  end
  def thu_by?(n)
    thus.exists?(book_id: n)
  end
  def fri_by?(n)
    fris.exists?(book_id: n)
  end
  def sat_by?(n)
    sats.exists?(book_id: n)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to :user

  
end

app/models/fri.rb
class Fri < ApplicationRecord
  belongs_to :book
end

app/models/holiday.rb
class Holiday < ApplicationRecord
  belongs_to :book
end

app/models/momment.rb
class Momment < ApplicationRecord
end

app/models/mon.rb
class Mon < ApplicationRecord
  belongs_to :book
end

app/models/sat.rb
class Sat < ApplicationRecord
  belongs_to :book
end

app/models/thu.rb
class Thu < ApplicationRecord
  belongs_to :book
end

app/models/tue.rb
class Tue < ApplicationRecord
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy

  def comment_by?(n,m)
    comments.exists?(book_id: n,user_id: m)
  end
end

app/models/wed.rb
class Wed < ApplicationRecord
  belongs_to :book
end

app/models/week.rb
class Week < ApplicationRecord
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    date1 = Date.today
    @date1 = (date1 + (8-date1.wday))+14
    @date = Date.today
    
  end

  def index2
    @date = Date.today
  end

  def show
    @book = Book.find(params[:id])
    @date = Date.today
  end

  def create
    @date = Date.today
    book = Book.new(book_params)
    #book.start_i = @date-1
    #book.finish_i = @date+7
    if book.save
      redirect_to request.referer
    else
      flash[:notice] = "既に作られている日程です"
      redirect_to request.referer
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:start_i, :finish_i)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/fris_helper.rb
module FrisHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/mons_helper.rb
module MonsHelper
end

app/helpers/sats_helper.rb
module SatsHelper
end

app/helpers/thus_helper.rb
module ThusHelper
end

app/helpers/tues_helper.rb
module TuesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weds_helper.rb
module WedsHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/books/_day.html.erb
<th>
  <% if book.mon_by?(book.id) %>
    <%= link_to book_mons_path(book.id), data: { turbo_method: :delete } ,:style=>"color: red" do %>
    <div style="color: red">
      <%= book.start_i.month %>月<%= book.start_i.day %>日
    </div>
    <% end %>
  <% else %>
    <%= link_to book_mons_path(book.id), data: { turbo_method: :post } ,:style=>"color: black" do %>
    <%= book.start_i.month %>月<%= book.start_i.day %>日
    <% end %>
  <% end %>
</th>
<th>
  <% if book.tue_by?(book.id) %>
    <div style="color: red">
      <%= (book.start_i+1).month %>月<%= (book.start_i+1).day %>日
    </div>
  <% else %>
    <%= (book.start_i+1).month %>月<%= (book.start_i+1).day %>日
  <% end %>
</th>
<th>
  <% if book.wed_by?(book.id) %>
    <div style="color: red">
      <%= (book.start_i+2).month %>月<%= (book.start_i+2).day %>日
    </div>
  <% else %>
    <%= (book.start_i+2).month %>月<%= (book.start_i+2).day %>日
  <% end %>
</th>
<th>
  <% if book.thu_by?(book.id) %>
      <div style="color: red">
        <%= (book.start_i+3).month %>月<%= (book.start_i+3).day %>日
      </div>
  <% else %>

      <%= (book.start_i+3).month %>月<%= (book.start_i+3).day %>日

  <% end %>
</th>
<th>
  <% if book.fri_by?(book.id) %>
    <div style="color: red">
      <%= (book.start_i+4).month %>月<%= (book.start_i+4).day %>日
    </div>
  <% else %>
    <%= (book.start_i+4).month %>月<%= (book.start_i+4).day %>日
  <% end %>
</th>
<th>
  <% if book.sat_by?(book.id) %>
    <div style="color: red">
      <%= (book.start_i+5).month %>月<%= (book.start_i+5).day %>日
    </div>
  <% else %>
    <div style="color: blue">
      <%= (book.start_i+5).month %>月<%= (book.start_i+5).day %>日
    </div>
  <% end %>
</th>
<th>
  <div style="color: red">
    <%= (book.start_i+6).month %>月<%= (book.start_i+6).day %>日
  </div>
</th>

app/views/books/_form.html.erb
<%= form_with model:[book,Comment.new], url:book_comments_path(book.id), method: :post do |f| %>
  <%= f.label :comment, "コメント" %>
  <%= f.text_field :comment %>

  <%= f.label :user_id, "ユーザー名" %>
  <%= f.collection_select :user_id, User.all, :id, :name, include_blank: "選択してね" %>

  <%= f.submit "投稿" %>
<% end %>

app/views/books/_login.html.erb
<%= form_with model: Momment.new, url: momments_path, method: :post do |f| %>
  <%= f.collection_select :momment_id, User.all, :id, :name, include_blank: "選択してね" %>
  <%= f.submit "選択" %>
<% end %>

<% Momment.all.each do |m| %>
  <%= m.id %>
  <%= m.momment_id %>
  <%= link_to "削除", momment_path(m.id), data: { turbo_method: :delete } %>
<% end %>

app/views/books/_week.html.erb
<td>
  <% if book.mon_by?(book.id) %>
    <%= link_to book_mons_path(book.id), data: { turbo_method: :delete } ,:style=>"color: red" do %>
      月
    <% end %>
  <% else %>
    <%= link_to book_mons_path(book.id), data: { turbo_method: :post } ,:style=>"color: black" do %>
      月
    <% end %>
  <% end %>
</td>
<td>
  <% if book.tue_by?(book.id) %>
    <%= link_to book_tues_path(book.id), data: { turbo_method: :delete } ,:style=>"color: red" do %>
      火
    <% end %>
  <% else %>
    <%= link_to book_tues_path(book.id), data: { turbo_method: :post } ,:style=>"color: black" do %>
      火
    <% end %>
  <% end %>
</td>
<td>
  <% if book.wed_by?(book.id) %>
    <%= link_to book_weds_path(book.id), data: { turbo_method: :delete } ,:style=>"color: red" do %>
      水
    <% end %>
  <% else %>
    <%= link_to book_weds_path(book.id), data: { turbo_method: :post } ,:style=>"color: black" do %>
      水
    <% end %>
  <% end %>
</td>
<td>
  <% if book.thu_by?(book.id) %>
    <%= link_to book_thus_path(book.id), data: { turbo_method: :delete } ,:style=>"color: red" do %>
      木
    <% end %>
  <% else %>
    <%= link_to book_thus_path(book.id), data: { turbo_method: :post } ,:style=>"color: black" do %>
      木
    <% end %>
  <% end %>
</td>
<td>
  <% if book.fri_by?(book.id) %>
    <%= link_to book_fris_path(book.id), data: { turbo_method: :delete } ,:style=>"color: red" do %>
      金
    <% end %>
  <% else %>
    <%= link_to book_fris_path(book.id), data: { turbo_method: :post } ,:style=>"color: black" do %>
      金
    <% end %>
  <% end %>
</td>
<td>
  <% if book.sat_by?(book.id) %>
    <%= link_to book_sats_path(book.id), data: { turbo_method: :delete } ,:style=>"color: red" do %>
      土
    <% end %>
  <% else %>
    <%= link_to book_sats_path(book.id), data: { turbo_method: :post } ,:style=>"color: blue" do %>
      土
    <% end %>
  <% end %>
</td>
<td style="color: red">日</td>

app/views/books/index.html.erb
<h1>一覧ページ</h1>
<hr>
<h2>今日</h2>
<%= @date %>
<h2>新規</h2>
<%= flash[:notice] %>
<%= form_with model: Book.new, url:books_path, method: :post do |f| %>
  <%= f.date_field :start_i, value: @date1 %>～<%= f.date_field :finish_i, value: @date1+6 %>
  <%= f.submit "作成" %>
<% end %>
<hr>
<h2>一覧</h2>
<%= link_to "バックアップ", past_path %><br>
<% Book.all.each do |book| %>
  <% if @date < book.start_i %>
    <%= book.id %>
  <%= link_to book_path(book.id) do %>
    <%= book.start_i %>～<%= book.finish_i %>
  <% end %>
  　<%= link_to "削除", book_path(book.id), data: { turbo_method: :delete } %>
  <br>
  <% end %>


<% end %>

app/views/books/index2.html.erb
<h2>過去のデータ</h2>
<% Book.all.each do |book| %>
  <% if @date > book.start_i %>
    <%= book.id %>
    <%= link_to book_path(book.id) do %>
      <%= book.start_i %>～<%= book.finish_i %>
    <% end %>
    　<%= link_to "削除", book_path(book.id), data: { turbo_method: :delete } %>
    <br>
  <% end %>
<% end %>

app/views/books/show.html.erb
<h1>投稿ごとのページ</h1>
<p>Find me in app/views/books/show.html.erb</p>
<%= link_to "戻る", books_path %>
<h2>ログインユーザー</h2>
<%= render "login" %>
<hr>
<%= @book.id %>
<%= @book.start_i %>～<%= @book.finish_i %>
<%= link_to "削除", book_path(@book.id), data: { turbo_method: :delete } %>
<hr>
<% if @book.week_by?(@book.id) %>
a
<%= link_to "削除", book_weeks_path(@book.id), data: { turbo_method: :delete } %>
<% else %>
b
<%= link_to "投稿", book_weeks_path(@book.id), data: { turbo_method: :post } %>
<% end %>

<table>
  <tr>
    <%= render "day", book:@book %>
    
  </tr>
  <tr>
    <%= render "week", book:@book %>
  </tr>
</table>
<hr>
<h3>コメント一覧</h3>
<%= Book.find(params[:id]).id %>
<br>
<% Comment.all.each do |comment| %>
  <%= comment.id %>
  <%= comment.book_id %>
  <%= comment.comment %>
  <%= link_to "削除", book_comment_path(comment.id), data: { turbo_method: :delete } %>
  <%= comment.user_id %>
  <br>
<% end %>
<hr>
<h3>ユーザー一覧からコメント</h3>
<% User.all.each do |user| %>
  <%= user.id %>
  <%= user.name %>
  <% if user.comment_by?(@book.id,user.id) %>
    〇
    <%= user.comments.each do |comment| %>
      <% if @book.id == comment.book_id && user.id == comment.user_id %>
        <%= comment.comment %>
        <%= link_to "削除", book_comment_path(comment.id), data: { turbo_method: :delete } %>  
      <% end %>
    <% end %>
  <% else %>
    ×
    <%= render "form", book:@book %>
  <% end %>
  <br>
<% end %>
    